make:
	gcc -o bin/build src/main.c src/headers/VectorPath.c src/headers/VectorPoint.c src/headers/VecLetter.c src/headers/fbp.c src/headers/f_image.c -lm
run :
	make
	./bin/build
clean:
	rm "bin/build"